// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./src/components/vo/Address.vue')['default']
    AddressDetailGrid: typeof import('./src/components/ui/AddressDetailGrid.vue')['default']
    BaseDetailGrid: typeof import('./src/components/base-ui/BaseDetailGrid.vue')['default']
    BaseEntity: typeof import('./src/components/base-ui/BaseEntity.vue')['default']
    BaseGrid: typeof import('./src/components/base-ui/BaseGrid.vue')['default']
    BasePicker: typeof import('./src/components/base-ui/BasePicker.vue')['default']
    BaseSecurity: typeof import('./src/components/base-ui/BaseSecurity.vue')['default']
    Boolean: typeof import('./src/components/primitives/Boolean.vue')['default']
    BuyNow: typeof import('./src/@core/components/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    Date: typeof import('./src/components/primitives/Date.vue')['default']
    Email: typeof import('./src/components/vo/Email.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    EventViewer: typeof import('./src/components/vo/EventViewer.vue')['default']
    File: typeof import('./src/components/vo/File.vue')['default']
    GetInventory: typeof import('./src/components/GetInventory.vue')['default']
    GetInventoryView: typeof import('./src/components/GetInventoryView.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    Inventory: typeof import('./src/components/Inventory.vue')['default']
    InventoryGrid: typeof import('./src/components/ui/InventoryGrid.vue')['default']
    InventoryId: typeof import('./src/components/InventoryId.vue')['default']
    InventoryIdDetailGrid: typeof import('./src/components/ui/InventoryIdDetailGrid.vue')['default']
    LargeObject: typeof import('./src/components/primitives/LargeObject.vue')['default']
    ModifyOrderinfo: typeof import('./src/components/ModifyOrderinfo.vue')['default']
    Money: typeof import('./src/components/vo/Money.vue')['default']
    MyPageView: typeof import('./src/components/MyPageView.vue')['default']
    Number: typeof import('./src/components/primitives/Number.vue')['default']
    Order: typeof import('./src/components/Order.vue')['default']
    OrderGrid: typeof import('./src/components/ui/OrderGrid.vue')['default']
    Payment: typeof import('./src/components/vo/Payment.vue')['default']
    Photo: typeof import('./src/components/vo/Photo.vue')['default']
    PhotoDetailGrid: typeof import('./src/components/ui/PhotoDetailGrid.vue')['default']
    Placeorder: typeof import('./src/components/Placeorder.vue')['default']
    Rating: typeof import('./src/components/vo/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    String: typeof import('./src/components/primitives/String.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    User: typeof import('./src/components/vo/User.vue')['default']
    Weather: typeof import('./src/components/vo/Weather.vue')['default']
  }
}
